### ISSUE TITLE
Command.js

### ISSUE THREAD

**Issue by Ayfri** [Les-Laboratoires-JS/command-handler#3]
Le fichier est vide :c

Et sinon je comprends pas pourquoi tu as mis `|` comme argument des permissions :thinking:

**Comment by loockeeer** [comment]
Quel fichier ? src/Classes/Commands.js ? Si oui, c'est normal.

Ensuite, le pipe permet de faire des permissions conditionnelles :
```js
["SEND_MESSAGES", "|", ["KICK_MEMBERS", "&", "BAN_MEMBERS"]]
```

**Comment by loockeeer** [comment]
Ce qui donne donc :
soit send messages, soit kick members ET ban members

**Comment by loockeeer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/2eMaiZ3I/1-test)
